### ISSUE TITLE
Problem building in Vercel

### ISSUE THREAD

**Issue by darrenmeehan** [mauriciabad/dive-log#5]
I really like this project and want to run it myself, I’m having trouble deploying it to Vercel myself though.

I’ve created an empty database in Planetscale, using Prisma as the project type, and added the connection string to my app in Vercel.

The app is failing to build though, am I missing expected environment variables? 

Could I get a list of what these should be? The README mentions asking for this, but I think having example values would be helpful!

```
> dive-log@0.1.0 build
> next build
❌ Invalid environment variables:
 NEXT_PUBLIC_DATABASE_ENV: Required
error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
> Build error occurred
Error: Invalid environment variables
    at file:///vercel/path0/src/env/client.mjs:22:9
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Error: Command "npm run build" exited with 1
```

**Comment by mauriciabad** [comment]
Hi, the `NEXT_PUBLIC_DATABASE_ENV` env variable should be this (in production):

```ini
NEXT_PUBLIC_DATABASE_ENV='production'
```

And for your development environment this:

```ini
NEXT_PUBLIC_DATABASE_ENV='test'
```

**Comment by mauriciabad** [comment]
I added an example `.env.example` file, so it is clear what variables are used.

https://github.com/mauriciabad/dive-log/blob/main/.env.example

Replace `aaaaaaaaaa` with the actual values.

**Comment by darrenmeehan** [comment]
Amazing thank you!

I'll try again and get back to you.

**Comment by mauriciabad** [comment]
If you just want to self-host it, I recommend you remove the OAuth options and just keep the GitHub one, that is the easiest to configure and maintain.

**Comment by darrenmeehan** [comment]
What makes the others difficult to maintain?

I was looking at the auth setup and we could conditionally add each provider by checking for the existence of the environment variables for each provider.

I'm only interested in Github for myself, possibly Google if I extend to others.

**Comment by mauriciabad** [comment]
Facebook changed the way it works and now it asks for tour ID and other company details i don't like giving that info. (Instagram the same) 

Google requires you to submit a form with a privacy policy. It's actually okay because i already did it so it should be easy.

Discord is actually super simple, but very few people use it.

**Comment by darrenmeehan** [comment]
Thanks for the insight!

I'm happy to just use Github for myself. I've a PR up to make them optional so people can choose what OAuth provider they want to use.

They'll have to change the code to add in a provider outside of those imported but I guess they can PR that change in if that happens?

**Comment by mauriciabad** [comment]
Yes, if someone wants to add a provider, they can open a PR. And if it's for a self-hosted instance, they can just fork the repo and change it as they like.
