### ISSUE TITLE
Lack of license for repository

### ISSUE THREAD

**Issue by darrenmeehan** [mauriciabad/dive-log#9]
I think it would be useful to have a license file included in the repository. It’s great you’re sharing the code; thank you! 

I think you’ll get more traction from users if it’s clear what is allowed etc.

Github has a decent overview here

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by mauriciabad** [comment]
True, I added MIT license
